### ISSUE TITLE
Will not compile with openssl 1.1.1a

### ISSUE THREAD

**Issue by rnejdl** [wkhtmltopdf/wkhtmltopdf#4214]
**wkhtmltopdf version(s) affected**: 12.5

**OS information**
12.0-RELEASE FreeBSD 12.0-RELEASE r342545 GENERICamd64

**Description**
Won't compile with OpenSSL 1.1.1a-freebsd  20 Nov 2018

**How to reproduce**
Attempt to make the port with openssl from base (not ports):
c++ -c -O2 -pipe -fno-strict-aliasing -march=nocona -DLIBICONV_PLUG -fstack-protector -DLIBICONV_PLUG -std=gnu++98 -O2 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -pthread -D_THREAD_SAFE -fPIC -DENABLE_VIDEO=0 -DQT_BUILD_NETWORK_LIB -DQT_NO_USING_NAMESPACE -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_NO_DEBUG -DQT_CORE_LIB -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I/usr/ports/converters/wkhtmltopdf/work/qt-5db36ec/mkspecs/freebsd-g++ -I/usr/ports/converters/wkhtmltopdf/work/qt-5db36ec/src/network -I../../include/QtCore -I../../include -I../../include/QtNetwork -I.rcc/release-static -I/usr/ports/converters/wkhtmltopdf/work/qt-5db36ec/src/network/kernel-I.moc/release-static -I/usr/local/include -I. -o .obj/release-static/qnetworkaccessmanager.o /usr/ports/converters/wkhtmltopdf/work/qt-5db36ec/src/network/access/qnetworkaccessmanager.cpp
/usr/ports/converters/wkhtmltopdf/work/qt-5db36ec/src/network/ssl/qsslsocket_openssl_symbols.cpp:825:5: error: 
use of undeclared identifier '_q_CRYPTO_free'; did you mean 'CRYPTO_free'?
RESOLVEFUNC(CRYPTO_free)
^
/usr/ports/converters/wkhtmltopdf/work/qt-5db36ec/src/network/ssl/qsslsocket_openssl_symbols.cpp:364:11: note: 
expanded from macro 'RESOLVEFUNC'
if (!(_q_##func = _q_PTR_##func(libs.first->resolve(#func)))     \
^
<scratch space>:173:1: note: expanded from here
_q_CRYPTO_free
^
/usr/include/openssl/crypto.h:276:6: note: 'CRYPTO_free' declared here
void CRYPTO_free(void *ptr, const char *file, int line);c++ -c -O2 -pipe -fno-strict-aliasing -march=nocona -DLIBICONV_PLUG -fstack-protector -DLIBICONV_PLUG -std=gnu++98 -O2 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -pthread-D_THREAD_SAFE -fPIC -DENABLE_VIDEO=0 -DQT_BUILD_NETWORK_LIB -DQT_NO_USING_NAMESPACE -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_NO_DEBUG -DQT_CORE_LIB -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I/usr/ports/converters/wkhtmltopdf/work/qt-5db36ec/mkspecs/freebsd-g++ -I/usr/ports/converters/wkhtmltopdf/work/qt-5db36ec/src/network -I../../include/QtCore -I../../include -I../../include/QtNetwork -I.rcc/release-static -I/usr/ports/converters/wkhtmltopdf/work/qt-5db36ec/src/network/kernel -I.moc/release-static -I/usr/local/include -I. -o .obj/release-static/qnetworkreplyimpl.o /usr/ports/converters/wkhtmltopdf/work/qt-5db36ec/src/network/access/qnetworkreplyimpl.cpp
^
/usr/ports/converters/wkhtmltopdf/work/qt-5db36ec/src/network/ssl/qsslsocket_openssl_symbols.cpp:825:5: error: 
use of undeclared identifier '_q_PTR_CRYPTO_free'
RESOLVEFUNC(CRYPTO_free)
^
/usr/ports/converters/wkhtmltopdf/work/qt-5db36ec/src/network/ssl/qsslsocket_openssl_symbols.cpp:364:23: note: 
expanded from macro 'RESOLVEFUNC'
if (!(_q_##func = _q_PTR_##func(libs.first->resolve(#func)))     \
^
<scratch space>:174:1: note: expanded from here
_q_PTR_CRYPTO_free
^
/usr/ports/converters/wkhtmltopdf/work/qt-5db36ec/src/network/ssl/qsslsocket_openssl_symbols.cpp:825:5: error: 
use of undeclared identifier '_q_CRYPTO_free'; did you mean 'CRYPTO_free'?
/usr/ports/converters/wkhtmltopdf/work/qt-5db36ec/src/network/ssl/qsslsocket_openssl_symbols.cpp:365:14: note: 
expanded from macro 'RESOLVEFUNC'
&& !(_q_##func = _q_PTR_##func(libs.second->resolve(#func)))) \
^
<scratch space>:175:1: note: expanded from here
_q_CRYPTO_free
^
/usr/include/openssl/crypto.h:276:6: note: 'CRYPTO_free' declared here
void CRYPTO_free(void *ptr, const char *file, int line);
^
/usr/ports/converters/wkhtmltopdf/work/qt-5db36ec/src/network/ssl/qsslsocket_openssl_symbols.cpp:825:5: error: 
use of undeclared identifier '_q_PTR_CRYPTO_free'
RESOLVEFUNC(CRYPTO_free)
^
/usr/ports/converters/wkhtmltopdf/work/qt-5db36ec/src/network/ssl/qsslsocket_openssl_symbols.cpp:365:26: note: 
expanded from macro 'RESOLVEFUNC'
&& !(_q_##func = _q_PTR_##func(libs.second->resolve(#func)))) \
^
<scratch space>:176:1: note: expanded from here
_q_PTR_CRYPTO_free
^
4 errors generated.
gmake[2]: *** [Makefile:17995: .obj/release-static/qsslsocket_openssl_symbols.o]Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: Leaving directory '/usr/ports/converters/wkhtmltopdf/work/wkhtmltopdf-0.12.5/build/qt/src/network'
gmake[1]: *** [Makefile:276: sub-network-all-ordered] Error 2
gmake[1]: Leaving directory '/usr/ports/converters/wkhtmltopdf/work/wkhtmltopdf-0.12.5/build/qt'
===> Compilation failed unexpectedly.
Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
the maintainer.
*** Error code 1
Stop.
make: stopped in /usr/ports/converters/wkhtmltopdf

**Expected behavior**
It compiles :)

**Possible Solution**  
Use openssl from ports but that is an older version.

**Comment by rnejdl** [comment]
Yes indeed this does solve the problem.  Sorry for guessing the wrong
spot to report this.  This can be closed out as resolved in the
distribution.  Thank you all! 

Rusty Nejdl

On 2019-01-05 16:28, Rainer Duffner wrote:

> Apparently fixed: 
> 
> https://svnweb.freebsd.org/ports/head/converters/wkhtmltopdf/Makefile?r1=489390&r2=489389&pathrev=489390 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4214#issuecomment-451696856
[2]
