### ISSUE TITLE
jQuery >= 3.3.0 $().html()

### ISSUE THREAD

**Issue by slaakso** [wkhtmltopdf/wkhtmltopdf#4341]
**wkhtmltopdf version(s) affected**:  0.12.5 (with patched qt)

**OS information**
MacOS 10.14.4

**Description**
Using jQuery's html() fails.

**How to reproduce**
```
<!DOCTYPE html>
<html lang="en">
<head>
  <script src="https://code.jquery.com/jquery-3.4.0.js"></script>
</head>
<body>
  <div id="test"></div>
  <script>
    var tmp = document.createElement('div');
    tmp.innerHTML = 'a';
    window.console.warn('Before html()');
    $('#test').html(tmp);
    window.console.warn('After html()');
  </script>
</body>
</html>
```

```
$ wkhtmltopdf --debug-javascript wk.html debug_output2.pdf
Loading pages (1/6)
Warning: file:///Users/user/tmp/wk.html:8 Before html()
Warning: undefined:0 TypeError: 'undefined' is not a function
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done                                
```
**Expected behavior**
With jQuery < 3.3.0 code works fine. Breaks with 3.3.0.

Any suggestions?

**Comment by slaakso** [comment]
More info after some debugging:

"`typeof document.querySelectorAll('script')`" comes up as `function` in wkhtmltopdf whereas it should be `object`. This causes jQuery's append() to fail which then causes html() to fails .

**Comment by Bhoft** [comment]
I also have the same issue my page works flawlessly with older versions of jQuery.  
It works with JQuery version 3.2.1 but with 3.3.0, 3.3.1, 3.4.0 i always got the "warning".

    Warning: https://cdn.jsdelivr.net/npm/jquery@3.3.0/dist/jquery.js:3813 jQuery.Deferred exception: 'undefined' is not a function
    Warning: undefined:0 TypeError: 'undefined' is not a function

and my JS code isn't executed.

**Comment by irbian** [comment]
> It works with JQuery version 3.2.1 

I found the same problem when updating to jQuery 3.4

Did you found everything ok when updating to 3.2.1?

**Comment by ashkulz** [comment]
I suspect this is due to the very old browser engine used by wkhtmltopdf, not sure anything can be done unless it gets upgraded (which may take a long time).

**Comment by bagnus** [comment]
Following slaakso info, I discovered that (at least in my case) the bug also affected the functions: .appendTo() and .after().

My application uses also jquery UI and changing the UI source was impratical (over one-hundred calls to modify), so I made a quick & dirty ovverun of the jquery original affected functions with a wrapping js file, to be loaded after jQuery 3.

```
/**
* Override jquery >= 3.3.1 functions because of wkhtml2pdf 12.5 issues
* 
* load module after jquery 
*/


/**
 * .html()
 * 
 * $(target).html()
 * $(target).html(contentToWrite)
 * 
 */

(function ($) {
  var originalHtml = $.fn.html;
  $.fn.html = function(par) {   
    if (arguments.length >= 1) {  
    	//write mode      
        if( typeof par == 'object') {
            //console.log('>> html with element '+par[0].id);
            $(this).empty();
            this[0].appendChild(par[0]);
            return this;
        }
        return originalHtml.call(this,par);
    }
    return originalHtml.call(this);
  };
})(jQuery);


/**
 * .append()
 * 
 * $(target).append(contentToBeAppended)
 * 
 */
(function ($) {
  var originalAppend = $.fn.append;
  $.fn.append = function(par) {
      if (arguments.length >= 1 && typeof par == 'object') {
          //console.log('>> append '+(typeof par)+' '+par[0].id+ ' to '+ (typeof this));
          this[0].appendChild(par[0]);
          return this;
      }
      return originalAppend.call(this, par);
  };
})(jQuery);


/**
 * .after()
 * 
 * $(target).after(contentToBeInserted)
 */
(function ($) {
    var originalAfter = $.fn.after;
    $.fn.after = function(par) {
      if (arguments.length >= 1 && typeof par == 'object') {
          //console.log('>> after with element '+par[0].id);
          this[0].parentNode.insertBefore(par[0], this[0].nextSibling);
          return this;
      }
      return originalAfter.call(this, par);
    };
  })(jQuery);


/**
 * .appendTo()
 * 
 * $(contentToBeAppended).appendTo(jqTarget)
 */
(function ($) {
    var originalAppendTo = $.fn.appendTo;
    $.fn.appendTo = function(par) {
      if (arguments.length >= 1 && typeof par == 'object') {
          //console.log('>> appendTo '+(typeof this[0])+' '+this[0].id+ ' to '+ par[0].id);
          par[0].appendChild(this[0]);
          return this;
      }
      return originalAppendTo.call(this, par);
    };
  })(jQuery);

```
It doesn't cover all situations, but in my case, solved the problem.
Feel free to replicate / modify / integrated the code.
The console.log() fragments were used to show in wkhtmltopdf debug mode some values and can be deleted.

Hope to save somebody's time...

**Comment by Bhoft** [comment]
@bagnus thank you very much. this code also helped, the pdf generation now works with jQuery 3.4.1 (at least in my case)

**Comment by bagnus** [comment]
@Bhoft: 

Step 1: you have to switch on the debug mode in wkhtmltopdf. I work in PHP and this is done inside a class with the command 
`exec($cmd, $this->exmsg,$this->ret);`
where $cmd is the wk command and others two are local vars.

Then you can see the result with:
```
echo ($this->exmsg);  // wk working steps
echo($this->ret);      // wk return
die;
```
the `die;` permit you to see what is happened.

Step 2: enable javascript debug with the flag `--debug-javascript` in the wk command
In this way you will be able to [almost] see a console.log output. The output is under the form of a warning with a url, but at the end of the line there is the console output.

Step 3: in your js module / widget, put lots of numbered `console.log('step #xxx');` at intervals in the code

Step 4: try several times to generate pdf. The last step #xxx before the failure message (in the wk debug mode) will give you a guess of the position of the offending function. If necessary, add more console.log().

Every Jquery function that does some element insert (and all the derivate methods) ex: before(), after(), insertBefore(), etc. is a good candidate.

Once you find the offending function, you need to write a wrapping with the insert made in plain js without jquery cmd.

Of course all this is a ugly patch. The best thing would be to make a ovverride of the "real" obsolete wk function. According to **slaakso** that would be document.querySelectorAll() returning a wrong type. I verified it and tried to write a js wrap, but even if it worked off-line, wk still gave me error. Than I ran out of time...

If somebody wish to try the wrap to document.querySelectorAll(), here is my attempt:

```
/**
 * Override standard js function querySelectorAll in wkhtmltopdf
 *
 *
 */  
if (typeof document.querySelectorAll('#dummy') != 'object') {
    // only if obsolete browser engine
   document.obsoQuerySelectorAll = document.querySelectorAll;
   document.querySelectorAll = function(par) {
           //console.log('step1');      
        // nodeList template (see https://jsfiddle.net/3y61e4de/)
        var list,
        nodeListProto = Object.create({}, {
            item: {
                value: function(x) {
                    return (Object.getOwnPropertyNames(this).indexOf(x.toString(10)) > -1) ? this[x] : null;
                },
                enumerable: true
            },
            length: {
                get: function() {
                    return Object.getOwnPropertyNames(this).length;
                },
                enumerable: true
            }
        }),
        getNodeList = function(nodes) {
            var n, eN = nodes.length,
                list = Object.create(nodeListProto);
            for (n = 0; n < eN; n++) { // for loop iterates also a nodelist if that was passed
                Object.defineProperty(list, n.toString(), {
                    value: nodes[n],
                    enumerable: true
                });
            }
            return (list.length) ? list : null;
        };
            //console.log('step2');      
       
        // get obso result
        var obsoArray = [],
            obso = document.obsoQuerySelectorAll(par);
        // create array of elements
        for (var k=0; k<obso.length; k++) {
            //console.log('index '+k+' = '+obso[k]);
            obsoArray[k] = obso[k];
        }
        // conversion to static nodeList
        return getNodeList(obsoArray);
    }     
}
```

**Comment by veeKewl** [comment]
> Following slaakso info, I discovered that (at least in my case) the bug also affected the functions: .appendTo() and .after().
> 
> My application uses also jquery UI and changing the UI source was impratical (over one-hundred calls to modify), so I made a quick & dirty ovverun of the jquery original affected functions with a wrapping js file, to be loaded after jQuery 3.
> 
> ```
> /**
> * Override jquery >= 3.3.1 functions because of wkhtml2pdf 12.5 issues
> * 
> * load module after jquery 
> */
> 
> 
> /**
>  * .html()
>  * 
>  * $(target).html()
>  * $(target).html(contentToWrite)
>  * 
>  */
> 
> (function ($) {
>   var originalHtml = $.fn.html;
>   $.fn.html = function(par) {   
>     if (arguments.length >= 1) {  
>     	//write mode      
>         if( typeof par == 'object') {
>             //console.log('>> html with element '+par[0].id);
>             $(this).empty();
>             this[0].appendChild(par[0]);
>             return this;
>         }
>         return originalHtml.call(this,par);
>     }
>     return originalHtml.call(this);
>   };
> })(jQuery);
> 
> 
> /**
>  * .append()
>  * 
>  * $(target).append(contentToBeAppended)
>  * 
>  */
> (function ($) {
>   var originalAppend = $.fn.append;
>   $.fn.append = function(par) {
>       if (arguments.length >= 1 && typeof par == 'object') {
>           //console.log('>> append '+(typeof par)+' '+par[0].id+ ' to '+ (typeof this));
>           this[0].appendChild(par[0]);
>           return this;
>       }
>       return originalAppend.call(this, par);
>   };
> })(jQuery);
> 
> 
> /**
>  * .after()
>  * 
>  * $(target).after(contentToBeInserted)
>  */
> (function ($) {
>     var originalAfter = $.fn.after;
>     $.fn.after = function(par) {
>       if (arguments.length >= 1 && typeof par == 'object') {
>           //console.log('>> after with element '+par[0].id);
>           this[0].parentNode.insertBefore(par[0], this[0].nextSibling);
>           return this;
>       }
>       return originalAfter.call(this, par);
>     };
>   })(jQuery);
> 
> 
> /**
>  * .appendTo()
>  * 
>  * $(contentToBeAppended).appendTo(jqTarget)
>  */
> (function ($) {
>     var originalAppendTo = $.fn.appendTo;
>     $.fn.appendTo = function(par) {
>       if (arguments.length >= 1 && typeof par == 'object') {
>           //console.log('>> appendTo '+(typeof this[0])+' '+this[0].id+ ' to '+ par[0].id);
>           par[0].appendChild(this[0]);
>           return this;
>       }
>       return originalAppendTo.call(this, par);
>     };
>   })(jQuery);
> ```
> 
> It doesn't cover all situations, but in my case, solved the problem.
> Feel free to replicate / modify / integrated the code.
> The console.log() fragments were used to show in wkhtmltopdf debug mode some values and can be deleted.
> 
> Hope to save somebody's time...

how do i use this ?

**Comment by bagnus** [comment]
**@ veeKewl :**

- save the code in a js module (es: myPatch.js),
- store the file somewhere in the server
- in your page load the module AFTER  jQuery 3

That's all :-)

**Comment by veeKewl** [comment]
@bagnus : do you have an overide for ``prependTo`` too ?

**Comment by bagnus** [comment]
**@ veeKewl :**

Sorry, no.
But you can add your own override function cloning  "appendTo"  one and changing the content for your needs. See "prepend elements with pure JavaScript" in the net

**Comment by jomann09** [comment]
Just figured I'd point out it looks like this is being fixed in the next version of jQuery (3.6) and I am using this patch https://github.com/jquery/jquery/pull/4757 along with the above overrides in order to make Highcharts work properly in wkhtmltopdf. So far it works.

**Comment by slaakso** [comment]
> Just figured I'd point out it looks like this is being fixed in the next version of jQuery (3.6, [jquery/jquery#4756](https://github.com/jquery/jquery/issues/4756)) and I am using the minor change as a patch on my jQuery 3.5.1 ( [jquery/jquery#4757](https://github.com/jquery/jquery/pull/4757)) along with the above overrides in order to make Highcharts work properly in wkhtmltopdf. So far it works.

**Comment by slaakso** [comment]
> Just figured I'd point out it looks like this is being fixed in the next version of jQuery (3.6, [jquery/jquery#4756](https://github.com/jquery/jquery/issues/4756)) and I am using the minor change as a patch on my jQuery 3.5.1 ( [jquery/jquery#4757](https://github.com/jquery/jquery/pull/4757)) along with the above overrides in order to make Highcharts work properly in wkhtmltopdf. So far it works.

Thank you for pointing this out. The fix from 3.6 seems to work.
