### ISSUE TITLE
0.12.5: undefined:0 TypeError: 'undefined' is not a function

### ISSUE THREAD

**Issue by ottcsconsult** [wkhtmltopdf/wkhtmltopdf#4251]
**wkhtmltopdf version(s) affected**: 0.12.5

**OS information**
Ubuntu 16.04
Mac OS X 10.12.6

**Description**
The following html/javascript throws (with --debug-javascript) 
<code>undefined:0 TypeError: 'undefined' is not a function</code>
and does not render anything.

<code>
<html>
  <body>
    <table>
      <tr><td class="mytest"></td></tr>
    </table>
    
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
    <script>
      var box = $(".mytest");
      box.append('<div>Hi!</div>');
    </script>
  </body>
</html>
</code>

**How to reproduce**
Save the above code as example.html

<code>wkthmltopdf --debug-javascript example.html output.pdf</code>

Nothing is rendered, warning is thrown.

**Expected behavior**
Hi! should appear on the page.

**Comment by ottcsconsult** [comment]
Update: Using jquery 1, this works.
```
<code><script src=“https://code.jquery.com/jquery-1.12.4.min.js” integrity=“sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=” crossorigin=“anonymous”></script>
```

**Comment by bakken1** [comment]
The issue could be how long it takes to load the js file. Try adding the `--no-stop-slow-scripts` flag and see if anything changes? (Found here: https://wkhtmltopdf.org/usage/wkhtmltopdf.txt)

**Comment by bjh** [comment]
we have been seeing this error since updating to rails 5 and jquery 3...have not found a fix yet.

**Comment by BARNZ** [comment]
Yeah same problem here under 0.12.5 on windows. 

The example seems to works fine with jquery 2.2.4:
<script src="https://code.jquery.com/jquery-2.2.4.min.js" crossorigin="anonymous"></script>

**Comment by dalisay** [comment]
Encountered this issue recently. I have tried all the workarounds to fix the loading issue - setOnLoadCallback, delays, setInterval, setTimeout. Also tried upgrading the wkhtml version.

What worked for me is explicitly define the Google Charts version number to use. In my case version 44.

`<script>google.load("visualization", "44", {packages:["corechart"]});</script>`

Note: using version "1" now means you are using the current version. Per Google document - "All 'jsapi' requests are now being redirected to the new loader. If you were loading version '1' or '1.0', you will now be loading 'current'."

**Comment by Montintin** [comment]
Can confirm @dalisay solution works 
> `<script>google.load("visualization", "44", {packages:["corechart"]});</script>`

I also tested with this and works fine
<script>google.charts.load('44', {packages: ['corechart']});</script>

**Comment by bentoabreu** [comment]
I changed 'current' to '44' and it work  google.charts.load('44', {'packages':['corechart']});

Thanks for the tip

**Comment by akaspick** [comment]
So '44' worked, but '45' or higher doesn't work.
