### ISSUE TITLE
wkhtmltopdf not compiling

### ISSUE THREAD

**Issue by saeohioalpha** [wkhtmltopdf/wkhtmltopdf#3335]
This issue happens with both 0.12.4 and the 0.12.5-dev branch.

> /opt/git_storage/wkhtmltopdf/src/lib/multipageloader.cc: In constructor ‘wkhtmltopdf::ResourceObject::ResourceObject(wkhtmltopdf::MultiPageLoaderPrivate&, const QUrl&, const wkhtmltopdf::settings::LoadPage&)’:
> /opt/git_storage/wkhtmltopdf/src/lib/multipageloader.cc:252:10: error: ‘class wkhtmltopdf::MyQWebPage’ has no member named ‘setDevicePixelRatio’
>   webPage.setDevicePixelRatio(devicePixelRatio); // Fix CSS media queries (does not affect anything else).
>           ^
> Makefile:390: recipe for target 'multipageloader.o' failed
> make[1]: *** [multipageloader.o] Error 1
> make[1]: *** Waiting for unfinished jobs....
> make[1]: Leaving directory '/opt/git_storage/wkhtmltopdf/static-build/posix-local/app/src/lib'
> Makefile:41: recipe for target 'sub-src-lib-make_default-ordered' failed
> make: *** [sub-src-lib-make_default-ordered] Error 2
> make -j2
> command failed: exit code 512

I was able to get wkhtmltopdf_0.12.5-dev to compile by removing this line from multipageloader.cc, and PDFs appear to be rendered exactly as the 0.12.3 version that was already installed. 

I ran the build with posix-local on ubuntu-15.10. I realize this is an outdated version of ubuntu, but the setDevicePixelRatio function is QWebPage adapter, and it shouldn't matter the version of ubuntu.

[http://code.qt.io/cgit/qt/qtwebkit.git/commit/?id=1d31917d872f0b9c1f87cbdf51fd20c771bdfc84
](http://code.qt.io/cgit/qt/qtwebkit.git/commit/?id=1d31917d872f0b9c1f87cbdf51fd20c771bdfc84
)
This link to the code looks to be for QTWebkit 5.8, I don't know if the functions are present in the version used by wkhtmltopdf on the master branch.

I had already ran:
```
git pull origin master
git fetch
git submodule update
```

**Comment by efx** [comment]
Also seeing this failure when attempting to update Alpine Linux's version: 
https://github.com/alpinelinux/aports/pull/942

**Comment by saeohioalpha** [comment]
I should note I've had no problems running wkhtmltopdf since I compiled with this line removed.

Been testing with a portion of users and all PDFs rendered fine for us.

**Comment by efx** [comment]
thanks @saeohioalpha that is quite helpful. I created a patch with that workaround for now.
@ashkulz can you shed some light on this? thanks!

**Comment by ashkulz** [comment]
This was fixed in af95531eabb212ae16a9fb689bb25a767eb580bc.

**Comment by keshcode** [comment]
Is this fixed ,  i currently started facing again on master.
