### ISSUE TITLE
Floating point exception (via C-bindings)

### ISSUE THREAD

**Issue by anowell** [wkhtmltopdf/wkhtmltopdf#3051]
I'm authoring the [rust wrapper](https://github.com/anowell/wkhtmltopdf-rs) and I occasionally hit a `floating point exception` during the call to `wkhtmltopdf_convert`. 

I can repro it, but it seems pretty specific:

1. I can only repro it setting `page` to a URL that does a <meta> redirect (been using https://www.rust-lang.org)
2. So far I can only repro with my high-level bindings. If I make all the exact wkhtmltopdf calls back-to-back in C or even with my low-level rust bindings, it doesn't repro (specific to memory layout?)  
3. Even then, it only repros about 10-20% of the time, and works as expected the rest of the time

I'd be happy to get a gdb stack trace if you have a build with debug symbols (0.12.3 for linux-generic-x64). I spent a couple hours trying unsuccessfully to build it myself (error below if it's immediately helpful, but not the problem I'm looking to solve):

```
/home/anowell/tmp/wkhtmltopdf-pkg/src/wkhtmltopdf/qt/src/xmlpatterns/api/qcoloroutput_p.h:74:60: error: shift expression ‘(1048575 << 20)’ overflows [-fpermissive]
/home/anowell/tmp/wkhtmltopdf-pkg/src/wkhtmltopdf/qt/src/xmlpatterns/api/qcoloroutput_p.h:74:63: error: enumerator value for ‘BackgroundMask’ is not an integer constant
             BackgroundMask  = ((1 << BackgroundShift) - 1) << BackgroundShift
```

**Comment by PhilterPaper** [comment]
I would suspect that `1048575 << 20`, when it overflows (during _constant expression evaluation_? Is this a constant value?), is producing a floating point (or other non-32 bit-integer) value, leading to the enumerator error in the following error message. 1048575 is xFFFFF, which certainly can't be left-shifted 20 bits and still fit in a (presumably) 32 bit integer. Any idea what this value represents, where it comes from, and why it's being left-shifted 20 bits? Going to 64 bit integers might solve the immediate problem, but that's probably not the right solution.

**Comment by anowell** [comment]
looks like a constant expression [here](https://github.com/wkhtmltopdf/qt/blob/fe194f9dac0b515757392a18f7fc9527c91d45ab/src/xmlpatterns/api/qcoloroutput_p.h#L74)

My reading of that code is that `ForegroundMask` is bits 10-19, and the `BackgroundMask` is bits 20-39 when it's probably supposed to be bits 20-29. So I presume the fix is something like:

```
ForegroundMask  = ((1 << 10) - 1) << ForegroundShift,
BackgroundMask = ((1 << 10) - 1) << BackgroundShift
```

It'd probably be forgiving with a 64-bit integer since I don't see anything leveraging any higher bits, but I'm a bit confused because as far as I can tell those are regular `int`s and I was building for 64-bit, so umm.. yeah... either way, I've got more pressing things to solve than building qt; I only tried to build it thinking it would "just work" and enable me to provide better diagnostics to the segfaults and issues like this one that I've been hitting while authoring wkhtmltopdf rust bindings.
