### ISSUE TITLE
[0.12.x] ES6 to ES5 issue using google/traceur-compiler

### ISSUE THREAD

**Issue by laguiz** [wkhtmltopdf/wkhtmltopdf#2326]
I'm using AngularJS and it seems that ES6 is coming. To convert ES6 to **ES5** we have different options. One of them (most popular?) is to use https://github.com/google/traceur-compiler . Using runtime in browser or transpilling before generare no javascript code to run and warnings are showed in logs (`TypeError: 'undefined' is not a function ` and `ReferenceError: Can't find variable: XXXXX`).

In my real world case I observed what is reproduced bellow and I suspect some polyfill missing but as indicated in https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2225 we cannot get more information for now in `0.12`.

1. Do you have any recommendation how we can investigate?
2. My main concern is to have a visibility of when `0.13` could be release (because `0.13` works as explain bellow) or if we can help to fix the issue in `0.12`.

I will try with https://babeljs.io/ when I find some time.

See https://github.com/laguiz/wkhtmltopdf-issue-traceur to reproduce the issue (pretty easy).

# Illustration of wkhtmltopdf issue with google/traceur-compiler

## My Config

- wkhtmltopdf 0.12.2.1 (with patched qt)
- Macos 10.10.2

## How to reproduce the issue ?

- You need node installed (or any http serveur)
- `git clone git@github.com:laguiz/wkhtmltopdf-issue-traceur.git`
- `cd wkhtmltopdf-issue-traceur`
- (with node) `http-server` in root folder
- Go to http://127.0.0.1:8080/ and make sure you see `Static message` AND `Hello, world!`
- Open new console and try to reproduce doing : `wkhtmltopdf --javascript-delay 2000 --debug-javascript http://127.0.0.1:8080/ resultko.pdf`

## Result observed

The `Hello, world!` message does not show and logs display this :

```
Loading pages (1/6)
Warning: undefined:0 TypeError: 'undefined' is not a function     
Warning: undefined:0 ReferenceError: Can't find variable: traceur
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done    
```

## Tested with 0.13 and it's ok

Tested on Windows 7 with this build http://downloads.sourceforge.net/wkhtmltopdf/wkhtmltox-0.13.0-alpha-7b36694_msvc2013-win64.exe and javscript works properly. Hower in my real case I got CSS and other issues probably due to the alpha version of the 0.13 branch.

Here is the output for 0.13 :

```
> "C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe" --debug-javascript  http://localhost:8080/ resultok.pdf
Loading page (1/2)
Printing pages (2/2)
Done
```

**Comment by ashkulz** [comment]
It's unlikely that it will be ever fixed in the `0.12.x` series, you might consider upgrading to 0.13.x when it gets released. What are the CSS/other issues you are facing with 0.13?

**Comment by laguiz** [comment]
Hi, thank you for you quick response.

in fact I was expecting this answer.

Quickly I can say that it's like the css and fonts are not loaded properly if not loaded at all.

You can close this issue I will reopen one for this css specific to `0.13` issue. I keep you up to date to this css issue.

**Comment by RopoMen** [comment]
Hi,
I had issue with AngularJS 1.5.0 and wkhtmltopdf 0.12 and I was able to get it working with 0.13-alpha, but because it is alpha we cannot take it in to use. My solution was to revert in to AngularJS 1.4.9 and start waiting this 0.13 to be released.

When can I expect this to happen? :)

**Comment by laguiz** [comment]
A bit off the current topic I can say that http://www.qtweb.net/ has been very helpful to debug some javascript errors (errors not directly related to this issue). @RopoMen If you don't really know what is not working you may want to try AngularJS 1.5.0 and the proper version of QtWeb to get more information.
Can't wait for version 0.13.
