### ISSUE TITLE
Unable to convert any page

### ISSUE THREAD

**Issue by charleschen0611** [wkhtmltopdf/wkhtmltopdf#4716]
**wkhtmltopdf version(s) affected**: 0.12.6 (with patched qt)

**OS information**
10.13.6

**Description**
The package was installed successfully without an issue. However, when I tried to use it, the following issue happened:

Loading pages (1/6)
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/bin/wkhtmltopdf
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/bin/wkhtmltopdf
  Expected in: /usr/lib/libSystem.B.dylib

**How to reproduce**
wkhtmltopdf http://google.com google.pdf

**Expected behavior**
I was tring to convert wiki pages to pdf for future use. But this issue happened. And it happened to all the webpages. I tried to uninstall wkhtmltopdf and reinstall it for multiple times. The issue still exists.

**Possible Solution**  
Also tried the following method, doesn't work... : 
brew cask reinstall wkhtmltopdf

Any help would be highly appreciated!!

**Comment by mzemel** [comment]
+1 on this, just encountered it as well.

**Comment by mzemel** [comment]
+1 on this, just encountered it as well.

@charleschen0611 

I downloaded the [0.12.5 package](https://github.com/wkhtmltopdf/wkhtmltopdf/releases/0.12.5/), and that worked for me.  I think this is a bug in the latest release.

**Comment by ashkulz** [comment]
@charleschen0611 @mzemel: are both of you using `10.13`? Unfortunately, I don't use macOS all that much so I guess this is a regression due to updating the builds to run on Catalina.

Can you confirm if it works on `10.14`?

**Comment by ashkulz** [comment]
@charleschen0611 @mzemel: can you let me know if [this build](https://builds.wkhtmltopdf.org/) from
the [`macos` branch](https://github.com/wkhtmltopdf/packaging/commits/macos) works for you?

**Comment by ashkulz** [comment]
I've submitted a PR: Homebrew/homebrew-cask#84388 -- hopefully you can just do `brew cask upgrade` and have it working in a few hours 🤞

**Comment by mzemel** [comment]
@ashkulz Thank you!  Apologies for not being available to help test.  0.12.6-2 works!

**Comment by charleschen0611** [comment]
@mzemel 
It worked for me too! Many thanks!

**Comment by brother-ur** [comment]
@ashkulz hi! Got the same error with version 0.12.6.5, downgrade to 0.12.5 solves the problem.
My system is High Sierra 10.13.6. If you give me a hint where I need to look at it, I'll try to fix it.

**Comment by ashkulz** [comment]
There is no `0.12.6.5`, where did you download it from? You should've gotten it from `brew install --cask wkhtmltopdf` or via [this release](https://github.com/wkhtmltopdf/packaging/releases/tag/0.12.6-2).

**Comment by brother-ur** [comment]
Sorry, I was a bit in a mess. It was not about your library, it was about ruby gem which is based on that. Gem has a similar version numbering, hence I messed up with the issue.
